name: CI for using Whatsapp
on: 
  push:
    branches: [main] #add with comma for more branches to monitor
  pull_request:
    branches: [main]
    
jobs: #job to execute?
  build: #name of the job
    name: Load OS # name for printing
    runs-on: ubuntu-latest # specify os in virtual machine
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Twilio-Whatsapp Action
  # You may pin to the exact commit or the version.
  # uses: mdb571/wa-action@a060b1dc0c137d4f889c23f0732f074c8ec7bf87
        uses: mdb571/wa-action@v1.0
        with:
          # The twilio whatsapp number from which the sms should be sent
          from: +1 (415) 523-8886
          # The number which is configured with twilio
          to: ${{ secrets.TWILIO_TO_WHATSAPP_NO}}
          # Twilio Accout SID from twilio console
          twilio_account_sid: ${{ secrets.twilio_account_sid }}
          # Twilio Authentication token from console
          twilio_auth: ${{ secrets.twilio_auth }}
